### ISSUE TITLE
masklint added to nixpkgs

### ISSUE THREAD

**Issue by pinage404** [brumhard/masklint#4]
Hello,

For your information, [this project has been packaged to nixpkgs](https://github.com/NixOS/nixpkgs/pull/330647)

It is now more easier for any [Nix](https://nixos.org/) user to use your package

```sh
nix-shell --packages masklint
```

https://search.nixos.org/packages?channel=unstable&type=packages&query=masklint

https://repology.org/project/masklint/versions

Feel free to close this issue

**Comment by brumhard** [comment]
@pinage404 awesome, thank you 🙏🏻
